#!/bin/bash

pwd
prj_name=$1
app_type=$2
port=3000
if [ $app_type != "-s" ]
then
  port=$(( ((RANDOM<<15)|RANDOM) % 63001 + 2000 ))
fi
echo "hosting port for app: "$port
mkdir -p "/home/gjcode/Politecnico/C/$prj_name/app/global-headers"
mkdir -p "/home/gjcode/Politecnico/C/$prj_name/app/project/src"
mkdir -p "/home/gjcode/Politecnico/C/$prj_name/app/project/headers"
mkdir -p "/home/gjcode/Politecnico/C/$prj_name/app/project/test"
mkdir -p "/home/gjcode/Politecnico/C/$prj_name/app/project/local-storage"
cd "$prj_name/"
cp -rf ./../global-headers/* ./app/global-headers/
cp -rf ./src/* ./app/project/src/
cp -rf ./headers/* ./app/project/headers/
cp -rf ./test/* ./app/project/test/
cp -rf ./local-storage/* ./app/project/local-storage/
cd "./app/project/src"
gcc -std=gnu99 -g -Wall -DTRACE -o myapp ./*
cmd='./myapp '
for (( i=3; i<"$#"+1; i++ ))
do
  cmd+=''${!i}''
  if [ $i -ne $# ]
  then
    cmd+=" "
  fi
done
$cmd
cd "../../../"
rm -R "./app"
