#!/bin/bash

prj_name=$1
app_type=$2
mkdir -p "$prj_name/src"
mkdir -p "$prj_name/headers"
mkdir -p "$prj_name/test"
mkdir -p "$prj_name/local-storage"
cp ./server-test/src/sockwrap.c "$prj_name/src"
cp ./server-test/src/errlib.c "$prj_name/src" 
if [ $app_type != "-s" ]
then
  touch	"$prj_name/src/client.c"
  cat <<EOF >> "$prj_name/src/client.c"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <netdb.h>
#include <arpa/inet.h>
#include<time.h>
#include <inttypes.h>

#include "../../global-headers/sockwrap.h"
#include "../../global-headers/errlib.h"

char *prog_name; // per evitare errori di compilazione

int main(int argc, char const *argv[])
{
    uint16_t port;
    struct sockaddr_in server_address;
    int sockfd;

    memset(&server_address, 0, sizeof(server_address)); 
    if (!inet_pton(AF_INET, argv[1], &server_address)) {
        printf("Address: " ANSI_COLOR_RED "INVALID ADDRESS" ANSI_COLOR_RESET "\n");
        err_msg("");
    }
    
    printf("Address: " ANSI_COLOR_GREEN "%s" ANSI_COLOR_RESET "\n", argv[1]);
    parsePort(argv[2], &port);
    sockfd = Socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);

    server_address.sin_family = AF_INET;
    server_address.sin_port = htons(port);

    ssize_t bytes_sent = 0;

    return 0;
}

EOF
		
else
  touch	"$prj_name/src/server.c"
  cat <<EOF >> "$prj_name/src/server.c" 
#include "../../global-headers/sockwrap.h"
#include "../../global-headers/errlib.h"
#include <time.h> 
#include <string.h>
#include <inttypes.h>
#include <errno.h>

char *prog_name; // per evitare errori di compilazione
int main(int argc, char const *argv[])
{
    uint16_t port;
    int sockfd;
    struct sockaddr_in client_addr;
    
    parsePort(argv[1], &port);

    return 0;
}

EOF
fi
