#!/bin/bash

prj_name=$1
app_type=$2
protocol=$3
mkdir -p "$prj_name/src"
mkdir -p "$prj_name/headers"
mkdir -p "$prj_name/test"
mkdir -p "$prj_name/local-storage"
cp -rf ./global-src/* "$prj_name/src/"
if [ $app_type != "-s" ]
then
  touch	"$prj_name/src/client.c"
  cat <<EOF >> "$prj_name/src/client.c"
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <time.h>
#include <inttypes.h>

#include "../../global-headers/sockwrap.h"
#include "../../global-headers/errlib.h"
#include "../../global-headers/gj_client.h"
#include "../../global-headers/gj_tools.h"

char *prog_name; // per evitare errori di compilazione

int main(int argc, char const *argv[]) {
    
    checkArgc(argc, "Usage: usage message here...");
    int connSock = connectTcpClient(argv[1],argv[2]);
    doClient(connSock, requestsHere);

    return 0;
}

EOF
		
if [ $protocol == "-tcp" ]
then
  touch	"$prj_name/src/server.c"
  cat <<EOF >> "$prj_name/src/server.c" 
#include "../../global-headers/sockwrap.h"
#include "../../global-headers/errlib.h"
#include <time.h> 
#include <string.h>
#include <inttypes.h>
#include <errno.h>

#include "../../global-headers/sockwrap.h"
#include "../../global-headers/errlib.h"
#include "../../global-headers/gj_server.h"
#include "../../global-headers/gj_tools.h"

char *prog_name; // per evitare errori di compilazione
int main(int argc, char const *argv[]) {
    
    checkArgc(argc, "Usage: <port>");
    int passiveSock = startTcpServer(INADDR_ANY, argv[1]);
    runTcpInstance(passiveSock);
    
    close(passiveSock);	

    return 0;
}

EOF
fi
